from enum import Enum


class Token(Enum):
    FLOATNUMBER = "liczba zmiennoprzecinkowa"
    BINNUMBER = "liczba binarna"
    OCTNUMBER = "liczba ósemkowa"
    HEXNUMBER = "liczba szesnastkowa"
    ID = "identyfikator"
    SPECIAL = "słowo kluczowe"
    STRING = "text"
    FSTRING = "f-string"
    PLUS = "+"
    MINUS = "-"
    MUL = "*"
    DIV = "/"
    DOUBLESLASH = "//"
    DOUBLESTAR = "**"
    PERCENT = "%"
    LPAREN = "("
    RPAREN = ")"
    LSQB = "["
    RSQB = "]"
    LBRACE = "{"
    RBRACE = "}"
    EQUAL = "="
    PLUSEQUAL = "+="
    MINUSEQUAL = "-="
    MULEQUAL = "*="
    DIVEQUAL = "/="
    DOUBLESLASHEQUAL = "//="
    COMPARISON = "=="
    NOTEQUAL = "!="
    LESS = "<"
    LESSEQUAL = "<="
    GREATER = ">"
    GREATEREQUAL = ">="
    COLON = ":"
    COMMA = ","
    DOT = "."
    BITAND = "&"
    BITOR = "|"
    NEWLINE = "\n"
    INDENT = "\t"
    SPACE = " "
    COMMENT = "#"
    ERROR = "?"
